services:
  mazeuploader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mazeuploader
    env_file:
      - .env
    restart: no
    mem_limit: 2g
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 1m
      timeout: 10s
      retries: 3
